name: adapt_log_uncatched_flutter_exception_input_adapter
description: Input adapter Flutter que captura automaticamente exceções não tratadas e as registra como logs de erro.
version: 1.0.0
repository: https://github.com/ranierjardim/dart_adapt_log

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  adapt_log:
    path: ../adapt_log/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
