name: adapt_log_report_log_input_adapter
description: Input adapter que emite reports — entries marcadas com contexto para transmissão ao servidor pelo adapter remoto.
version: 1.0.0
repository: https://github.com/ranierjardim/dart_adapt_log

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  adapt_log:
    path: ../adapt_log/

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
